[package]
name = "scx_utils"
version = "1.0.5"
edition = "2021"
authors = ["Tejun Heo <tj@kernel.org>"]
license = "GPL-2.0-only"
repository = "https://github.com/sched-ext/scx"
description = "Utilities for sched_ext schedulers"

[dependencies]
anyhow = "1.0.65"
bitvec = { version = "1.0", features = ["serde"] }
# FIXME - We need to allow both 0.68 and 0.69 to accommodate fedora. See the
# comment in BpfBuilder::bindgen_bpf_intf() for details.
bindgen = ">=0.68, <0.70"
glob = "0.3"
hex = "0.4.3"
lazy_static = "1.4"
libbpf-cargo = "0.24.1"
libbpf-rs = "0.24.1"
log = "0.4.17"
nvml-wrapper = { version = "0.10.0", optional = true }
paste = "1.0"
regex = "1.10"
scx_stats = { path = "../scx_stats", version = "1.0.5" }
serde = { version = "1.0", features = ["derive"] }
sscanf = "0.4"
tar = "0.4"
walkdir = "2.4"
version-compare = "0.1"
metrics = "0.23.0"
metrics-util = "0.17.0"
libc = "0.2.137"

[build-dependencies]
bindgen = ">=0.68, <0.70"
tar = "0.4"
vergen = { version = "8.0.0", features = ["cargo", "git", "gitcl"] }
walkdir = "2.4"

[features]
default = []
gpu-topology = ["dep:nvml-wrapper"]
