/* automatically generated by rust-bindgen 0.70.1 */
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

pub const scx_consts_SCX_DSP_DFL_MAX_BATCH: scx_consts = 32;
pub const scx_consts_SCX_DSP_MAX_LOOPS: scx_consts = 32;
pub const scx_consts_SCX_WATCHDOG_MAX_TIMEOUT: scx_consts = 30000;
pub const scx_consts_SCX_EXIT_BT_LEN: scx_consts = 64;
pub const scx_consts_SCX_EXIT_MSG_LEN: scx_consts = 1024;
pub const scx_consts_SCX_EXIT_DUMP_DFL_LEN: scx_consts = 32768;
pub const scx_consts_SCX_CPUPERF_ONE: scx_consts = 1024;
pub type scx_consts = ::std::os::raw::c_uint;
pub const scx_exit_kind_SCX_EXIT_NONE: scx_exit_kind = 0;
pub const scx_exit_kind_SCX_EXIT_DONE: scx_exit_kind = 1;
pub const scx_exit_kind_SCX_EXIT_UNREG: scx_exit_kind = 64;
pub const scx_exit_kind_SCX_EXIT_UNREG_BPF: scx_exit_kind = 65;
pub const scx_exit_kind_SCX_EXIT_UNREG_KERN: scx_exit_kind = 66;
pub const scx_exit_kind_SCX_EXIT_SYSRQ: scx_exit_kind = 67;
pub const scx_exit_kind_SCX_EXIT_ERROR: scx_exit_kind = 1024;
pub const scx_exit_kind_SCX_EXIT_ERROR_BPF: scx_exit_kind = 1025;
pub const scx_exit_kind_SCX_EXIT_ERROR_STALL: scx_exit_kind = 1026;
pub type scx_exit_kind = ::std::os::raw::c_uint;
