/* automatically generated by rust-bindgen 0.71.1 */

pub const __GENTOO_NOT_FREESTANDING: u32 = 1;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_60559_BFP__: u32 = 201404;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_IEC_60559_COMPLEX__: u32 = 201404;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __bool_true_false_are_defined: u32 = 1;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub type u8_ = ::std::os::raw::c_uchar;
pub type u32_ = ::std::os::raw::c_uint;
pub type u64_ = ::std::os::raw::c_ulonglong;
pub const consts_MAX_CPUS: consts = 512;
pub const consts_MAX_NUMA_NODES: consts = 64;
pub const consts_MAX_LLCS: consts = 64;
pub const consts_MAX_DSQS_PER_LLC: consts = 8;
pub const consts_NSEC_PER_USEC: consts = 1000;
pub const consts_NSEC_PER_MSEC: consts = 1000000;
pub const consts_MSEC_PER_SEC: consts = 1000;
pub const consts_NSEC_PER_SEC: consts = 1000000000;
pub const consts_CLOCK_BOOTTIME: consts = 7;
pub type consts = ::std::os::raw::c_uint;
pub const p2dq_timers_defs_EAGER_LOAD_BALANCER_TMR: p2dq_timers_defs = 0;
pub const p2dq_timers_defs_MAX_TIMERS: p2dq_timers_defs = 1;
pub type p2dq_timers_defs = ::std::os::raw::c_uint;
pub const stat_idx_P2DQ_STAT_DIRECT: stat_idx = 0;
pub const stat_idx_P2DQ_STAT_DSQ_SAME: stat_idx = 1;
pub const stat_idx_P2DQ_STAT_DSQ_CHANGE: stat_idx = 2;
pub const stat_idx_P2DQ_STAT_IDLE: stat_idx = 3;
pub const stat_idx_P2DQ_STAT_GREEDY_IDLE: stat_idx = 4;
pub const stat_idx_P2DQ_STAT_LB_SELECT: stat_idx = 5;
pub const stat_idx_P2DQ_STAT_LB_DISPATCH: stat_idx = 6;
pub const stat_idx_P2DQ_STAT_LLC_MIGRATION: stat_idx = 7;
pub const stat_idx_P2DQ_STAT_NODE_MIGRATION: stat_idx = 8;
pub const stat_idx_P2DQ_STAT_KEEP: stat_idx = 9;
pub const stat_idx_P2DQ_STAT_SELECT_PICK2: stat_idx = 10;
pub const stat_idx_P2DQ_STAT_DISPATCH_PICK2: stat_idx = 11;
pub const stat_idx_P2DQ_STAT_WAKE_PREV: stat_idx = 12;
pub const stat_idx_P2DQ_STAT_WAKE_LLC: stat_idx = 13;
pub const stat_idx_P2DQ_STAT_WAKE_MIG: stat_idx = 14;
pub const stat_idx_P2DQ_NR_STATS: stat_idx = 15;
pub type stat_idx = ::std::os::raw::c_uint;
pub const scheduler_mode_MODE_PERFORMANCE: scheduler_mode = 0;
pub type scheduler_mode = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct p2dq_timer {
    pub interval_ns: u64_,
    pub init_flags: u64_,
    pub start_flags: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of p2dq_timer"][::std::mem::size_of::<p2dq_timer>() - 24usize];
    ["Alignment of p2dq_timer"][::std::mem::align_of::<p2dq_timer>() - 8usize];
    ["Offset of field: p2dq_timer::interval_ns"]
        [::std::mem::offset_of!(p2dq_timer, interval_ns) - 0usize];
    ["Offset of field: p2dq_timer::init_flags"]
        [::std::mem::offset_of!(p2dq_timer, init_flags) - 8usize];
    ["Offset of field: p2dq_timer::start_flags"]
        [::std::mem::offset_of!(p2dq_timer, start_flags) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct task_ctx {
    pub dsq_id: u64_,
    pub dsq_index: ::std::os::raw::c_int,
    pub cpu: u32_,
    pub llc_id: u32_,
    pub node_id: u32_,
    pub runnable: bool,
    pub weight: u32_,
    pub last_dsq_id: u64_,
    pub last_dsq_index: ::std::os::raw::c_int,
    pub last_run_at: u64_,
    pub llc_runs: u64_,
    pub is_kworker: bool,
    pub all_cpus: bool,
    pub mask: *mut bpf_cpumask,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of task_ctx"][::std::mem::size_of::<task_ctx>() - 80usize];
    ["Alignment of task_ctx"][::std::mem::align_of::<task_ctx>() - 8usize];
    ["Offset of field: task_ctx::dsq_id"][::std::mem::offset_of!(task_ctx, dsq_id) - 0usize];
    ["Offset of field: task_ctx::dsq_index"][::std::mem::offset_of!(task_ctx, dsq_index) - 8usize];
    ["Offset of field: task_ctx::cpu"][::std::mem::offset_of!(task_ctx, cpu) - 12usize];
    ["Offset of field: task_ctx::llc_id"][::std::mem::offset_of!(task_ctx, llc_id) - 16usize];
    ["Offset of field: task_ctx::node_id"][::std::mem::offset_of!(task_ctx, node_id) - 20usize];
    ["Offset of field: task_ctx::runnable"][::std::mem::offset_of!(task_ctx, runnable) - 24usize];
    ["Offset of field: task_ctx::weight"][::std::mem::offset_of!(task_ctx, weight) - 28usize];
    ["Offset of field: task_ctx::last_dsq_id"]
        [::std::mem::offset_of!(task_ctx, last_dsq_id) - 32usize];
    ["Offset of field: task_ctx::last_dsq_index"]
        [::std::mem::offset_of!(task_ctx, last_dsq_index) - 40usize];
    ["Offset of field: task_ctx::last_run_at"]
        [::std::mem::offset_of!(task_ctx, last_run_at) - 48usize];
    ["Offset of field: task_ctx::llc_runs"][::std::mem::offset_of!(task_ctx, llc_runs) - 56usize];
    ["Offset of field: task_ctx::is_kworker"]
        [::std::mem::offset_of!(task_ctx, is_kworker) - 64usize];
    ["Offset of field: task_ctx::all_cpus"][::std::mem::offset_of!(task_ctx, all_cpus) - 65usize];
    ["Offset of field: task_ctx::mask"][::std::mem::offset_of!(task_ctx, mask) - 72usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cpu_ctx {
    pub id: ::std::os::raw::c_int,
    pub llc_id: u32_,
    pub node_id: u32_,
    pub dsq_index: u64_,
    pub perf: u32_,
    pub interactive: bool,
    pub is_big: bool,
    pub ran_for: u64_,
    pub dsqs: [u64_; 8usize],
    pub max_load_dsq: u64_,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cpu_ctx"][::std::mem::size_of::<cpu_ctx>() - 112usize];
    ["Alignment of cpu_ctx"][::std::mem::align_of::<cpu_ctx>() - 8usize];
    ["Offset of field: cpu_ctx::id"][::std::mem::offset_of!(cpu_ctx, id) - 0usize];
    ["Offset of field: cpu_ctx::llc_id"][::std::mem::offset_of!(cpu_ctx, llc_id) - 4usize];
    ["Offset of field: cpu_ctx::node_id"][::std::mem::offset_of!(cpu_ctx, node_id) - 8usize];
    ["Offset of field: cpu_ctx::dsq_index"][::std::mem::offset_of!(cpu_ctx, dsq_index) - 16usize];
    ["Offset of field: cpu_ctx::perf"][::std::mem::offset_of!(cpu_ctx, perf) - 24usize];
    ["Offset of field: cpu_ctx::interactive"]
        [::std::mem::offset_of!(cpu_ctx, interactive) - 28usize];
    ["Offset of field: cpu_ctx::is_big"][::std::mem::offset_of!(cpu_ctx, is_big) - 29usize];
    ["Offset of field: cpu_ctx::ran_for"][::std::mem::offset_of!(cpu_ctx, ran_for) - 32usize];
    ["Offset of field: cpu_ctx::dsqs"][::std::mem::offset_of!(cpu_ctx, dsqs) - 40usize];
    ["Offset of field: cpu_ctx::max_load_dsq"]
        [::std::mem::offset_of!(cpu_ctx, max_load_dsq) - 104usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct llc_ctx {
    pub id: u32_,
    pub nr_cpus: u32_,
    pub node_id: u32_,
    pub vtime: u64_,
    pub all_big: bool,
    pub dsqs: [u64_; 8usize],
    pub dsq_max_vtime: [u64_; 8usize],
    pub dsq_load: [u64_; 8usize],
    pub cpumask: *mut bpf_cpumask,
    pub big_cpumask: *mut bpf_cpumask,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of llc_ctx"][::std::mem::size_of::<llc_ctx>() - 240usize];
    ["Alignment of llc_ctx"][::std::mem::align_of::<llc_ctx>() - 8usize];
    ["Offset of field: llc_ctx::id"][::std::mem::offset_of!(llc_ctx, id) - 0usize];
    ["Offset of field: llc_ctx::nr_cpus"][::std::mem::offset_of!(llc_ctx, nr_cpus) - 4usize];
    ["Offset of field: llc_ctx::node_id"][::std::mem::offset_of!(llc_ctx, node_id) - 8usize];
    ["Offset of field: llc_ctx::vtime"][::std::mem::offset_of!(llc_ctx, vtime) - 16usize];
    ["Offset of field: llc_ctx::all_big"][::std::mem::offset_of!(llc_ctx, all_big) - 24usize];
    ["Offset of field: llc_ctx::dsqs"][::std::mem::offset_of!(llc_ctx, dsqs) - 32usize];
    ["Offset of field: llc_ctx::dsq_max_vtime"]
        [::std::mem::offset_of!(llc_ctx, dsq_max_vtime) - 96usize];
    ["Offset of field: llc_ctx::dsq_load"][::std::mem::offset_of!(llc_ctx, dsq_load) - 160usize];
    ["Offset of field: llc_ctx::cpumask"][::std::mem::offset_of!(llc_ctx, cpumask) - 224usize];
    ["Offset of field: llc_ctx::big_cpumask"]
        [::std::mem::offset_of!(llc_ctx, big_cpumask) - 232usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct node_ctx {
    pub id: u32_,
    pub all_big: bool,
    pub cpumask: *mut bpf_cpumask,
    pub big_cpumask: *mut bpf_cpumask,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of node_ctx"][::std::mem::size_of::<node_ctx>() - 24usize];
    ["Alignment of node_ctx"][::std::mem::align_of::<node_ctx>() - 8usize];
    ["Offset of field: node_ctx::id"][::std::mem::offset_of!(node_ctx, id) - 0usize];
    ["Offset of field: node_ctx::all_big"][::std::mem::offset_of!(node_ctx, all_big) - 4usize];
    ["Offset of field: node_ctx::cpumask"][::std::mem::offset_of!(node_ctx, cpumask) - 8usize];
    ["Offset of field: node_ctx::big_cpumask"]
        [::std::mem::offset_of!(node_ctx, big_cpumask) - 16usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bpf_cpumask {
    pub _address: u8,
}
