[package]
name = "scx_rustland_core"
version = "2.1.2"
edition = "2021"
authors = ["Andrea Righi <andrea.righi@linux.dev>"]
license = "GPL-2.0-only"
repository = "https://github.com/sched-ext/scx"
description = "Framework to implement sched_ext schedulers running in user space"

[dependencies]
anyhow = "1.0.65"
plain = "0.2.3"
libbpf-rs = "0.24.1"
libc = "0.2.137"
scx_utils = { path = "../scx_utils", version = "1.0.5" }

[build-dependencies]
tar = "0.4"
walkdir = "2.4"
scx_utils = { path = "../scx_utils", version = "1.0.5" }

[lib]
name = "scx_rustland_core"
path = "src/lib.rs"
include = [
    "assets/bpf/intf.h",
    "assets/bpf/main.bpf.c",
    "assets/bpf.rs",
]

