name: install-deps

runs:
  using: 'composite'
  steps:
    ### OTHER REPOS ####

    # Hard turn-off interactive mode
    - run: echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
      shell: bash

    # Refresh packages list
    - run: sudo apt update
      shell: bash

    ### DOWNLOAD AND INSTALL DEPENDENCIES ###

    # Download dependencies packaged by Ubuntu
    - run: sudo apt -y install bison busybox-static cargo cmake coreutils cpio elfutils file flex gcc gcc-multilib git iproute2 jq kbd kmod libcap-dev libelf-dev libunwind-dev libvirt-clients libzstd-dev linux-headers-generic linux-tools-common linux-tools-generic make ninja-build pahole pkg-config python3-dev python3-pip python3-requests qemu-kvm rsync rustc stress-ng udev zstd libseccomp-dev libcap-ng-dev llvm clang python3-full pipx curl meson
      shell: bash

    # virtme-ng
    - run: pip3 install virtme-ng --break-system-packages
      shell: bash

    # Setup KVM support
    - run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      shell: bash

    ### END DEPENDENCIES ###
